use nom::error::Error;
use nom::{
    IResult,
    branch::alt,
    bytes::complete::{tag, take_while},
    character::complete::{char, digit1},
    combinator::{map, opt, peek, recognize, value, verify},
    multi::{many0, separated_list0},
    sequence::{pair, terminated, tuple},
};
use tower_lsp::lsp_types::{Diagnostic, DiagnosticSeverity, Range};

use super::utils::calc_range;
use crate::ast::*;

use super::core::{
    is_keyword, parse_identifier, parse_non_keyword_identifier, whitespace_handler, ws,
};

const MAX_RECURSION_DEPTH: usize = 100;

// Expression Parsing
struct ParseContext {
    depth: usize,
}

impl ParseContext {
    fn new() -> Self {
        ParseContext { depth: 0 }
    }

    fn check_depth(&self) -> Result<(), nom::Err<Error<&'static str>>> {
        if self.depth >= MAX_RECURSION_DEPTH {
            Err(nom::Err::Error(Error::new(
                "",
                nom::error::ErrorKind::TooLarge,
            )))
        } else {
            Ok(())
        }
    }

    fn enter(&mut self) -> Result<(), nom::Err<Error<&'static str>>> {
        self.check_depth()?;
        self.depth += 1;
        Ok(())
    }

    fn exit(&mut self) {
        self.depth = self.depth.saturating_sub(1);
    }
}

/// Wrapper to extract range information from any parser.
/// Ex: with_range(original_input, parse_non_keyword_identifier)(i)
///
/// Generated by AI, give extra scrutiny here.
fn with_range<'a, F, O>(
    original_input: &'a str,
    mut parser: F,
) -> impl FnMut(&'a str) -> IResult<&'a str, (O, Range)>
where
    F: FnMut(&'a str) -> IResult<&'a str, O>,
{
    move |input: &'a str| {
        let start = input.as_ptr() as usize - original_input.as_ptr() as usize;
        let (input, out) = parser(input)?;
        let end = input.as_ptr() as usize - original_input.as_ptr() as usize;

        Ok((input, (out, calc_range(original_input, start, end - start))))
    }
}

/// Parses a keyword by its exact name with word-boundary checking.
fn parse_keyword<'a>(kw: &'static str) -> impl FnMut(&'a str) -> IResult<&'a str, &'a str> {
    move |input: &'a str| verify(parse_identifier, move |s: &str| s == kw)(input)
}

pub fn parse_expr<'a>(original_input: &'a str, input: &'a str, diags: &mut Vec<Diagnostic>) -> IResult<&'a str, Expr> {
    let (input, _) = whitespace_handler(input)?;

    let mut ctx = ParseContext::new();
    parse_expr_with_context(original_input, input, &mut ctx, diags)
}

fn parse_expr_with_context<'a>(
    original_input: &'a str,
    input: &'a str,
    ctx: &mut ParseContext,
    diags: &mut Vec<Diagnostic>
) -> IResult<&'a str, Expr> {
    ctx.enter()
        .map_err(|_| nom::Err::Error(Error::new(input, nom::error::ErrorKind::TooLarge)))?;
    let result = parse_let_expr(original_input, input, ctx, diags);
    ctx.exit();
    result
}

fn parse_let_expr<'a>(
    original_input: &'a str,
    input: &'a str,
    ctx: &mut ParseContext,
    diags: &mut Vec<Diagnostic>
) -> IResult<&'a str, Expr> {
    let start = input.as_ptr() as usize - original_input.as_ptr() as usize;

    // 1. Consume whitespace before 'let'
    let (input, _) = whitespace_handler(input)?;
    let (input, is_let) = opt(parse_keyword("let"))(input)?;

    if is_let.is_some() {
        // 2. Whitespace after 'let'
        let (input, _) = whitespace_handler(input)?;
        let (input, name) = match with_range(original_input, parse_non_keyword_identifier)(input) {
            Ok(r) => r,
            Err(e) => match e {
                nom::Err::Error(new_input) => {
                    // just assume it's missing, nothing there
                    let new_input_loc = new_input.input.as_ptr() as usize - original_input.as_ptr() as usize;
                    let range = calc_range(original_input, new_input_loc, 1);
                    diags.push(Diagnostic { 
                        range, 
                        severity: Some(DiagnosticSeverity::ERROR),
                        
                        source: Some("Parser".to_string()), 
                        message: "Missing an identifier in the let expression. Format: let [identifier] = [value] in [expression]".to_string(), ..Default::default()});

                    (new_input.input, (new_input.input, range))
                },
                _ => return Err(e) // gen unrecoverable
            },
        };

        // 3. Handle '=' with whitespace around it
        let (input, _) = whitespace_handler(input)?;
        let input = match char::<&str, Error<&str>>('=')(input) {
            Ok(r) => r.0, // matched it
            Err(e) => match e {
                nom::Err::Error(new_input) => {
                    // add diagnostic that the = was missing
                    // but, just move on anyway, as if we had the =
                    diags.push(Diagnostic { 
                        range: calc_range(original_input, new_input.input.as_ptr() as usize - original_input.as_ptr() as usize - 1, 1), 
                        severity: Some(DiagnosticSeverity::ERROR), 
                        source: Some("Parser".to_string()), 
                        message: "Need an = sign in let expr".to_string(), ..Default::default() });
                    new_input.input
                },
                _ => return Err(e),
            },
        };
        let (input, _) = whitespace_handler(input)?;

        let (input, value) = parse_if_expr(original_input, input, ctx, diags)?;

        // 4. Handle 'in' with whitespace around it
        let (input, _) = whitespace_handler(input)?;
        let input = match parse_keyword("in")(input) {
            Ok(r) => r.0,
            Err(e) => match e {
                nom::Err::Error(new_input) => {
                    // add diagnostic that the 'in' was missing
                    // but, just move on anyway, as if we had the 'in'
                    diags.push(Diagnostic { 
                        range: calc_range(original_input, new_input.input.as_ptr() as usize - original_input.as_ptr() as usize - 1, 1), 
                        severity: Some(DiagnosticSeverity::ERROR), 
                        source: Some("Parser".to_string()), 
                        message: "Need an \"in\" after the value for a let expr".to_string(), ..Default::default() });
                    new_input.input
                },
                _ => return Err(e),
                
            },
        };
        let (input, _) = whitespace_handler(input)?;

        let (input, body) = parse_expr_with_context(original_input, input, ctx, diags)?;

        let end = input.as_ptr() as usize - original_input.as_ptr() as usize;

        Ok((
            input,
            Expr::new(
                ExprKind::LetBinding {
                    name: RangedIdentifier {
                        string: name.0.to_string(),
                        range: name.1,
                    },
                    value: Box::new(value),
                    body: Box::new(body),
                },
                calc_range(original_input, start, end - start),
            ),
        ))
    } else {
        // Check for `match` expression before delegating to if/lambda/binary
        let (_, is_match) = opt(peek(ws(parse_keyword("match"))))(input)?;
        if is_match.is_some() {
            parse_match_expr(original_input, input, ctx, diags)
        } else {
            parse_if_expr(original_input, input, ctx, diags)
        }
    }
}

fn parse_if_expr<'a>(
    original_input: &'a str,
    input: &'a str,
    ctx: &mut ParseContext,
    diags: &mut Vec<Diagnostic>
) -> IResult<&'a str, Expr> {
    let start = input.as_ptr() as usize - original_input.as_ptr() as usize;

    // 1. Consume whitespace before 'if'
    let (input, _) = whitespace_handler(input)?;
    let (input, is_if) = opt(parse_keyword("if"))(input)?;

    if is_if.is_some() {
        // 2. Whitespace after 'if'
        let (input, _) = whitespace_handler(input)?;
        let (input, condition) = parse_lambda_expr(original_input, input, ctx, diags)?;

        // 3. Handle 'then' with whitespace around it
        let (input, _) = whitespace_handler(input)?;

        let before_usize = input.as_ptr() as usize;
        let input = match parse_keyword("then")(input) {
            Ok(r) => r.0,
            Err(e) => match e {
                nom::Err::Error(new_input) => {
                    diags.push(Diagnostic { 
                        range: calc_range(original_input, before_usize - original_input.as_ptr() as usize, new_input.input.as_ptr() as usize - before_usize), 
                        severity: Some(DiagnosticSeverity::ERROR), 
                        source: Some("Parser".to_string()), 
                        message: "Need a \"then\" after the condition for an if expr".to_string(), ..Default::default() });
                    new_input.input
                },
                _ => return Err(e),
            }
        };
        let (input, _) = whitespace_handler(input)?;

        let (input, then_branch) = parse_if_expr(original_input, input, ctx, diags)?;

        // 4. Handle 'else' with whitespace around it
        let (input, _) = whitespace_handler(input)?;
        let before_usize = input.as_ptr() as usize;
        let input = match parse_keyword("else")(input) {
            Ok(r) => r.0,
            Err(e) => match e {
                nom::Err::Error(new_input) => {
                    diags.push(Diagnostic { 
                        range: calc_range(original_input, before_usize - original_input.as_ptr() as usize, new_input.input.as_ptr() as usize - before_usize), 
                        severity: Some(DiagnosticSeverity::ERROR), 
                        source: Some("Parser".to_string()), 
                        message: "Need a \"else\" after the condition for an if expr".to_string(), ..Default::default() });
                    new_input.input
                },
                _ => return Err(e),
            }
        };
        let (input, _) = whitespace_handler(input)?;

        let (input, else_branch) = parse_if_expr(original_input, input, ctx, diags)?;

        let end = input.as_ptr() as usize - original_input.as_ptr() as usize;

        Ok((
            input,
            Expr::new(
                ExprKind::IfThenElse {
                    condition: Box::new(condition),
                    then_branch: Box::new(then_branch),
                    else_branch: Box::new(else_branch),
                },
                calc_range(original_input, start, end - start),
            ),
        ))
    } else {
        parse_lambda_expr(original_input, input, ctx, diags)
    }
}

fn parse_lambda_expr<'a>(
    original_input: &'a str,
    input: &'a str,
    ctx: &mut ParseContext,
    diags: &mut Vec<Diagnostic>
) -> IResult<&'a str, Expr> {
    let start = input.as_ptr() as usize - original_input.as_ptr() as usize;

    // 1. Whitespace before pipe '|'
    let (input, _) = whitespace_handler(input)?;
    let (input, is_lambda) = opt(char('|'))(input)?;

    if is_lambda.is_some() {
        let before_usize = input.as_ptr() as usize;
        let (input, params) = match separated_list0(
            |i| {
                let (i, _) = whitespace_handler(i)?;
                char(',')(i)
            },
            |i| {
                let (i, _) = whitespace_handler(i)?;
                with_range(original_input, parse_non_keyword_identifier)(i)
            },
        )(input) {
            Ok(r) => r,
            Err(e) => match e{
                nom::Err::Error(new_input) => {
                    // recovery on no separated list? or separated list had issue
                    // TODO fill this in
                    diags.push(Diagnostic { 
                        range: calc_range(original_input, before_usize - original_input.as_ptr() as usize, new_input.input.as_ptr() as usize - before_usize), 
                        severity: Some(DiagnosticSeverity::ERROR), 
                        source: Some("Parser".to_string()), 
                        message: "Could not evaluate parameters of lambda expression".to_string(), ..Default::default() });
                    (new_input.input, Vec::new())
                },
                _ => return Err(e)
            }
        };

        // 2. Handle closing pipe '|'
        let (input, _) = whitespace_handler(input)?;
        let before_usize = input.as_ptr() as usize;
        let input = match char::<&str, Error<&str>>('|')(input) {
            Ok(r) => r.0,
            Err(e) => match e{
                nom::Err::Error(new_input) => {
                    diags.push(Diagnostic { 
                        range: calc_range(original_input, before_usize - original_input.as_ptr() as usize, new_input.input.as_ptr() as usize - before_usize), 
                        severity: Some(DiagnosticSeverity::ERROR), 
                        source: Some("Parser".to_string()), 
                        message: "Lambda needs a closing | after the parameters".to_string(), ..Default::default() });
                    new_input.input
                },
                _ => return Err(e)
            }
        };

        // 3. Handle arrow '->' with whitespace around it
        let (input, _) = whitespace_handler(input)?;
        let before_usize = input.as_ptr() as usize;
        let input = match tag::<&str, &str, Error<&str>>("->")(input) {
            Ok(r) => r.0,
            Err(e) => match e{
                nom::Err::Error(new_input) => {
                    diags.push(Diagnostic { 
                        range: calc_range(original_input, before_usize - original_input.as_ptr() as usize, new_input.input.as_ptr() as usize - before_usize), 
                        severity: Some(DiagnosticSeverity::ERROR), 
                        source: Some("Parser".to_string()), 
                        message: "Lambda needs -> after closing | following parameters list".to_string(), ..Default::default() });
                    new_input.input
                },
                _ => return Err(e),
            }
        };
        let (input, _) = whitespace_handler(input)?;

        let (input, body) = parse_expr_with_context(original_input, input, ctx, diags)?;

        let end = input.as_ptr() as usize - original_input.as_ptr() as usize;

        Ok((
            input,
            Expr::new(
                ExprKind::Lambda {
                    params: params
                        .into_iter()
                        .map(|s| RangedIdentifier {
                            string: s.0.to_string(),
                            range: s.1,
                        })
                        .collect(),
                    body: Box::new(body),
                },
                calc_range(original_input, start, end - start),
            ),
        ))
    } else {
        parse_logical_or_expr(original_input, input, ctx, diags)
    }
}

fn parse_logical_or_expr<'a>(
    original_input: &'a str,
    input: &'a str,
    ctx: &mut ParseContext,
    diags: &mut Vec<Diagnostic>
) -> IResult<&'a str, Expr> {
    parse_binary_op(
        original_input,
        input,
        ctx,
        |o, i, c| parse_logical_and_expr(o, i, c, diags),
        alt((value(BinaryOperator::Or, ws(tag("||"))),)),
    )
}

fn parse_logical_and_expr<'a>(
    original_input: &'a str,
    input: &'a str,
    ctx: &mut ParseContext,
    diags: &mut Vec<Diagnostic>
) -> IResult<&'a str, Expr> {
    parse_binary_op(
        original_input,
        input,
        ctx,
        |o, i, c| parse_comparison_expr(o, i, c, diags),
        alt((value(BinaryOperator::And, ws(tag("&&"))),)),
    )
}

fn parse_comparison_expr<'a>(
    original_input: &'a str,
    input: &'a str,
    ctx: &mut ParseContext,
    diags: &mut Vec<Diagnostic>
) -> IResult<&'a str, Expr> {
    parse_binary_op(
        original_input,
        input,
        ctx,
        |o, i, c| parse_tensor_expr(o, i, c, diags),
        alt((
            value(BinaryOperator::Eq, ws(tag("=="))),
            value(BinaryOperator::Ne, ws(tag("!="))),
            value(BinaryOperator::Le, ws(tag("<="))),
            value(BinaryOperator::Ge, ws(tag(">="))),
            value(BinaryOperator::Lt, ws(char('<'))),
            value(BinaryOperator::Gt, ws(char('>'))),
        )),
    )
}

fn parse_tensor_expr<'a>(
    original_input: &'a str,
    input: &'a str,
    ctx: &mut ParseContext,
    diags: &mut Vec<Diagnostic>
) -> IResult<&'a str, Expr> {
    parse_binary_op(
        original_input,
        input,
        ctx,
        |o, i, c| parse_range_expr(o, i, c, diags),
        alt((value(
            BinaryOperator::Tensor,
            ws(alt((tag("⊗"), tag("tensor")))),
        ),)),
    )
}

fn parse_range_expr<'a>(
    original_input: &'a str,
    input: &'a str,
    ctx: &mut ParseContext,
    diags: &mut Vec<Diagnostic>
) -> IResult<&'a str, Expr> {
    parse_binary_op(
        original_input,
        input,
        ctx,
        |o, i, c| parse_additive_expr(o, i, c, diags),
        alt((value(BinaryOperator::Range, ws(tag(".."))),)),
    )
}

fn parse_additive_expr<'a>(
    original_input: &'a str,
    input: &'a str,
    ctx: &mut ParseContext,
    diags: &mut Vec<Diagnostic>
) -> IResult<&'a str, Expr> {
    parse_binary_op(
        original_input,
        input,
        ctx,
        |o, i, c| parse_multiplicative_expr(o, i, c, diags),
        alt((
            value(BinaryOperator::Add, ws(char('+'))),
            value(BinaryOperator::Sub, ws(char('-'))),
        )),
    )
}

fn parse_multiplicative_expr<'a>(
    original_input: &'a str,
    input: &'a str,
    ctx: &mut ParseContext,
    diags: &mut Vec<Diagnostic>
) -> IResult<&'a str, Expr> {
    parse_binary_op(
        original_input,
        input,
        ctx,
        |o, i, c| parse_unary_expr(o, i, c, diags),
        alt((
            value(BinaryOperator::Mul, ws(char('*'))),
            value(BinaryOperator::Div, ws(char('/'))),
            value(BinaryOperator::Mod, ws(char('%'))),
        )),
    )
}

fn parse_binary_op<'a, F, G>(
    original_input: &'a str,
    input: &'a str,
    ctx: &mut ParseContext,
    mut next_level: F,
    mut op_parser: G,
) -> IResult<&'a str, Expr>
where
    F: FnMut(&'a str, &'a str, &mut ParseContext) -> IResult<&'a str, Expr>,
    G: FnMut(&'a str) -> IResult<&'a str, BinaryOperator>,
{
    let start = input.as_ptr() as usize - original_input.as_ptr() as usize;
    let (input, left) = next_level(original_input, input, ctx)?;

    let (input, ops_and_rights) =
        many0(pair(&mut op_parser, |i| next_level(original_input, i, ctx)))(input)?;

    if ops_and_rights.is_empty() {
        return Ok((input, left));
    }

    let mut result = left;
    let current_start = start;

    for (op, right) in ops_and_rights {
        let end = input.as_ptr() as usize - original_input.as_ptr() as usize;
        result = Expr::new(
            ExprKind::BinaryOp {
                op,
                left: Box::new(result),
                right: Box::new(right),
            },
            calc_range(original_input, current_start, end - current_start),
        );
    }

    Ok((input, result))
}

fn parse_unary_expr<'a>(
    original_input: &'a str,
    input: &'a str,
    ctx: &mut ParseContext,
    diags: &mut Vec<Diagnostic>
) -> IResult<&'a str, Expr> {
    let start = input.as_ptr() as usize - original_input.as_ptr() as usize;

    let op_parse = alt((
        value(UnaryOperator::Not, ws(char('!'))),
        value(UnaryOperator::Neg, ws(char('-'))),
    ))(input);

    match op_parse {
        Ok((rest, op)) => {
            let (rest, operand) = parse_unary_expr(original_input, rest, ctx, diags)?;
            let end = rest.as_ptr() as usize - original_input.as_ptr() as usize;
            Ok((
                rest,
                Expr::new(
                    ExprKind::UnaryOp {
                        op,
                        operand: Box::new(operand),
                    },
                    calc_range(original_input, start, end - start),
                ),
            ))
        }
        Err(_) => parse_postfix_expr(original_input, input, ctx, diags),
    }
}

fn parse_postfix_expr<'a>(
    original_input: &'a str,
    input: &'a str,
    ctx: &mut ParseContext,
    diags: &mut Vec<Diagnostic>
) -> IResult<&'a str, Expr> {
    let (mut current_input, mut base) = parse_primary_expr(original_input, input, ctx, diags)?;
    let start = input.as_ptr() as usize - original_input.as_ptr() as usize;

    loop {
        if let Ok((rest, _)) = ws(char('.'))(current_input) {
            // Tuple Projection / Dynamic Indexing with Parentheses
            if let Ok((rest_inner, _)) = tag::<_, _, Error<&str>>("(")(rest) {
                // Tuple Projection .(0)
                if let Ok((rest_idx, idx_str)) = terminated(digit1, ws(char(')')))(rest_inner) {
                    let idx = idx_str.parse::<usize>().unwrap_or(0);
                    let end = rest_idx.as_ptr() as usize - original_input.as_ptr() as usize;

                    base = Expr::new(
                        ExprKind::Projection {
                            index: idx,
                            tuple: Box::new(base),
                        },
                        calc_range(original_input, start, end - start),
                    );
                    current_input = rest_idx;
                    continue;
                }

                // Dynamic Indexing .(expr)
                if let Ok((rest_final, index_expr)) = terminated(
                    |i| parse_expr_with_context(original_input, i, ctx, diags),
                    ws(char(')')),
                )(rest_inner) {
                    let end = rest_final.as_ptr() as usize - original_input.as_ptr() as usize;

                    base = Expr::new(
                        ExprKind::IndexAccess {
                            object: Box::new(base),
                            index: Box::new(index_expr),
                        },
                        calc_range(original_input, start, end - start),
                    );
                    current_input = rest_final;
                    continue;
                }
                
                // none of these, do something else
                // TODO fill this in
                let end = rest_inner.as_ptr() as usize - original_input.as_ptr() as usize;
                diags.push(Diagnostic { 
                    range: calc_range(original_input, start, end-start), 
                    severity: Some(DiagnosticSeverity::ERROR),
                    source: Some("Parser".to_string()), 
                    message: "Indexing with projection or dynamic failed.".to_string(), 
                    ..Default::default()
                });
                continue; // TODO what should we do here?

            }

            // Field access or Tuple Indexing
            if let Ok((rest_inner, field)) = alt((parse_identifier, digit1))(rest) {
                let end = rest_inner.as_ptr() as usize - original_input.as_ptr() as usize;
                base = Expr::new(
                    ExprKind::FieldAccess {
                        object: Box::new(base),
                        field: field.to_string(),
                    },
                    calc_range(original_input, start, end - start),
                );
                current_input = rest_inner;
                continue;
            }
        }

        // Indexing
        if let Ok((rest, _)) = ws(char('['))(current_input) {
            let (rest, index_expr) = parse_expr_with_context(original_input, rest, ctx, diags)?;
            let rest = match ws(char(']'))(rest) {
                Ok(r) => r.0,
                Err(e) => match e {
                    nom::Err::Error(new_input) => {
                        let end = new_input.input.as_ptr() as usize - original_input.as_ptr() as usize;
                        diags.push(Diagnostic { 
                            range: calc_range(original_input, start, end-start), 
                            severity: Some(DiagnosticSeverity::ERROR),
                            source: Some("Parser".to_string()), 
                            message: "Indexing with [] needs a closing ]".to_string(), 
                            ..Default::default()
                        });
                        new_input.input
                    },
                    _ => return Err(e)
                }
            };

            let end = rest.as_ptr() as usize - original_input.as_ptr() as usize;
            base = Expr::new(
                ExprKind::IndexAccess {
                    object: Box::new(base),
                    index: Box::new(index_expr),
                },
                calc_range(original_input, start, end - start),
            );
            current_input = rest;
            continue;
        }

        // Function call
        if let Ok((rest, _)) = ws(char('('))(current_input) {

            let res = separated_list0(ws(char(',')), |i| {
                //parse_expr_with_context(original_input, i, ctx)
                let (i, _) = whitespace_handler(i)?;
                let arg_start = i.as_ptr() as usize - original_input.as_ptr() as usize;
                let (i, mut expr) = parse_expr_with_context(original_input, i, ctx, diags)?;
                let arg_end = i.as_ptr() as usize - original_input.as_ptr() as usize;
                expr.range = calc_range(original_input, arg_start, arg_end - arg_start);
                Ok((i, expr))
            })(rest);
            let (rest, args) = match res {
                Ok(r) => r,
                Err(e) => match e {
                    nom::Err::Error(new_input) => {
                        let end = new_input.input.as_ptr() as usize - original_input.as_ptr() as usize;
                        diags.push(Diagnostic { 
                            range: calc_range(original_input, start, end-start), 
                            severity: Some(DiagnosticSeverity::ERROR),
                            source: Some("Parser".to_string()), 
                            message: "Function call arguments could not be parsed".to_string(), 
                            ..Default::default()
                        });
                        (new_input.input, Vec::new())

                    },
                    _ => return Err(e),
                }
            };
            let rest = match ws(char(')'))(rest) {
                Ok(r) => r.0,
                Err(e) => match e {
                    nom::Err::Error(new_input) => {
                        let end = new_input.input.as_ptr() as usize - original_input.as_ptr() as usize;
                        diags.push(Diagnostic { 
                            range: calc_range(original_input, start, end-start), 
                            severity: Some(DiagnosticSeverity::ERROR),
                            source: Some("Parser".to_string()), 
                            message: "Function call needs closing ) after arguments".to_string(), 
                            ..Default::default()
                        });
                        new_input.input
                    },
                    _ => return Err(e),
                }
            };

            let end = rest.as_ptr() as usize - original_input.as_ptr() as usize;
            base = Expr::new(
                ExprKind::FunctionCall {
                    function: Box::new(base),
                    args,
                },
                calc_range(original_input, start, end - start),
            );
            current_input = rest;
            continue;
        }

        break;
    }

    Ok((current_input, base))
}

fn parse_primary_expr<'a>(
    original_input: &'a str,
    input: &'a str,
    ctx: &mut ParseContext,
    diags: &mut Vec<Diagnostic>
) -> IResult<&'a str, Expr> {
    let start: usize = input.as_ptr() as usize - original_input.as_ptr() as usize;

    if let Ok((rest, _)) = ws(tag("None"))(input) {
        return Ok((
            rest,
            Expr::new(ExprKind::None, calc_range(original_input, start, 4)),
        ));
    }
    if let Ok((rest, _)) = ws(tag("true"))(input) {
        return Ok((rest, Expr::bool(true, calc_range(original_input, start, 4))));
    }
    if let Ok((rest, _)) = ws(tag("false"))(input) {
        return Ok((
            rest,
            Expr::bool(false, calc_range(original_input, start, 5)),
        ));
    }
    if let Ok((rest, val)) = parse_number(original_input)(input) {
        return Ok((rest, val));
    }
    if let Ok((rest, val)) = parse_string_literal(original_input)(input) {
        return Ok((rest, val));
    }

    if let Ok((rest, _)) = ws(tag("Some"))(input) {
        let (rest, _) = ws(char('('))(rest)?;
        let (rest, expr) = parse_expr_with_context(original_input, rest, ctx, diags)?;
        let (rest, _) = ws(char(')'))(rest)?;

        let end = rest.as_ptr() as usize - original_input.as_ptr() as usize;
        return Ok((
            rest,
            Expr::new(
                ExprKind::Some(Box::new(expr)),
                calc_range(original_input, start, end - start),
            ),
        ));
    }

    // List literal
    if let Ok((rest, _)) = ws(char('['))(input) {
        let res = separated_list0(ws(char(',')), |i| {
            parse_expr_with_context(original_input, i, ctx, diags)
        })(rest);

        let (rest, exprs) = match res {
            Ok(r) => r,
            Err(e) => match e {
                nom::Err::Error(new_input) => {
                    let end = new_input.input.as_ptr() as usize - original_input.as_ptr() as usize;
                        diags.push(Diagnostic { 
                            range: calc_range(original_input, start, end-start), 
                            severity: Some(DiagnosticSeverity::ERROR),
                            source: Some("Parser".to_string()), 
                            message: "List literal arguments could not be parsed".to_string(), 
                            ..Default::default()
                        });
                    (new_input.input, Vec::new())
                },
                _ => return Err(e),
            }
        };
        let rest = match ws(char(']'))(rest) {
            Ok(r) => r.0,
            Err(e) => match e {
                nom::Err::Error(new_input) => {
                    let end = new_input.input.as_ptr() as usize - original_input.as_ptr() as usize;
                        diags.push(Diagnostic { 
                            range: calc_range(original_input, start, end-start), 
                            severity: Some(DiagnosticSeverity::ERROR),
                            source: Some("Parser".to_string()), 
                            message: "List literal needs an ending ]".to_string(), 
                            ..Default::default()
                        });
                    new_input.input
                },
                _ => return Err(e),
            }
        };

        let end = rest.as_ptr() as usize - original_input.as_ptr() as usize;
        return Ok((
            rest,
            Expr::new(
                ExprKind::List(exprs),
                calc_range(original_input, start, end - start),
            ),
        ));
    }

    // Tuple literal / Parenthesized expression
    if let Ok((rest, _)) = ws(char('('))(input) {
        let (rest, exprs) = separated_list0(ws(char(',')), |i| {
            parse_expr_with_context(original_input, i, ctx, diags)
        })(rest)?;
        let (rest, _) = ws(char(')'))(rest)?;

        let end = rest.as_ptr() as usize - original_input.as_ptr() as usize;
        if exprs.len() == 1 {
            return Ok((rest, exprs.into_iter().next().unwrap()));
        } else {
            return Ok((
                rest,
                Expr::new(
                    ExprKind::Tuple(exprs),
                    calc_range(original_input, start, end - start),
                ),
            ));
        }
    }

    // Struct literal or just identifier, last options

    // there are two options for how to write this part. need to test both TODO
    // 1. error if can't parse identifier, because this function couldn't parse
    // anything.
    // 2. silently pretend a primary was parsed, even if no identifier could be
    // parsed. in this case, need to make sure there are no infinite loops
    // happening where pretending something was parsed results in a problem

    // will for now go with option 2. if this fails, switch to option 1

    match parse_identifier(input) {
        Ok((rest_after_id, id_str)) => {
            if let Ok((_, _)) = peek(ws(char('{')))(rest_after_id)
            && !is_keyword(id_str)
        {
            let (rest, _) = ws(char('{'))(rest_after_id)?;
            let (rest, fields) = separated_list0(
                ws(char(',')),
                map(
                    tuple((parse_identifier, ws(char('=')), |i| {
                        parse_expr_with_context(original_input, i, ctx, diags)
                    })),
                    |(name, _, expr)| (name.to_string(), expr),
                ),
            )(rest)?;
            let (rest, _) = ws(char('}'))(rest)?;

            let end = rest.as_ptr() as usize - original_input.as_ptr() as usize;
            return Ok((
                rest,
                Expr::new(
                    ExprKind::StructLiteral {
                        name: id_str.to_string(),
                        fields,
                    },
                    calc_range(original_input, start, end - start),
                ),
            ));
        }

        let len = id_str.len();
        Ok((
            rest_after_id,
            Expr::identifier(id_str.to_string(), calc_range(original_input, start, len)),
        ))
        },
        Err(e) => match e {
            nom::Err::Error(new_input) => {
                let end = new_input.input.as_ptr() as usize - original_input.as_ptr() as usize;
                let range = calc_range(original_input, start, end-start);
                diags.push(Diagnostic { 
                    range,
                    severity: Some(DiagnosticSeverity::ERROR),
                    source: Some("Parser".to_string()), 
                    message: "Could not parse this expression.".to_string(), 
                    ..Default::default()
                });
                Err(nom::Err::Error(new_input))
            },
            _ => Err(e)
        }
    }
}

fn parse_match_expr<'a>(
    original_input: &'a str,
    input: &'a str,
    ctx: &mut ParseContext,
    diags: &mut Vec<Diagnostic>
) -> IResult<&'a str, Expr> {
    let start = input.as_ptr() as usize - original_input.as_ptr() as usize;

    // Consume `match` keyword
    let (input, _) = ws(parse_keyword("match"))(input)?;

    // Parse scrutinee — any expression up to `with`
    let (input, scrutinee) = parse_expr_with_context(original_input, input, ctx, diags)?;

    // Consume `with`
    let input = match ws(tag("with"))(input) {
        Ok(r) => r.0,
        Err(e) => match e {
            nom::Err::Error(new_input) => {
                let end = new_input.input.as_ptr() as usize - original_input.as_ptr() as usize;
                let range = calc_range(original_input, start, end-start);
                diags.push(Diagnostic { 
                    range,
                    severity: Some(DiagnosticSeverity::ERROR),
                    source: Some("Parser".to_string()), 
                    message: "Expected to find \"with\" in match".to_string(), 
                    ..Default::default()
                });
                new_input.input
            },
            _ => return Err(e)
        }
    };

    // Parse arms: `| pattern -> body`
    let mut arms = Vec::new();
    let mut current = input;
    while let Ok((rest, _)) = ws(char('|'))(current) {
        let (rest, pattern) = parse_match_pattern(rest)?;
        let rest = match ws(tag("->"))(rest) {
            Ok(r) => r.0,
            Err(e) => match e {
                nom::Err::Error(new_input) => {
                    let end = new_input.input.as_ptr() as usize - original_input.as_ptr() as usize;
                    let range = calc_range(original_input, start, end-start);
                    diags.push(Diagnostic { 
                        range,
                        severity: Some(DiagnosticSeverity::ERROR),
                        source: Some("Parser".to_string()), 
                        message: "Expected to find \"->\" in match arm".to_string(), 
                        ..Default::default()
                    });
                    new_input.input
                },
                _ => return Err(e)
            }
        };
        let (rest, body) = parse_expr_with_context(original_input, rest, ctx, diags)?;
        arms.push(MatchArm { pattern, body });
        current = rest;
    }

    if arms.is_empty() {
        return Err(nom::Err::Error(Error::new(
            current,
            nom::error::ErrorKind::Many1,
        )));
    }

    let end = current.as_ptr() as usize - original_input.as_ptr() as usize;
    Ok((
        current,
        Expr::new(
            ExprKind::Match {
                scrutinee: Box::new(scrutinee),
                arms,
            },
            calc_range(original_input, start, end - start),
        ),
    ))
}

fn parse_match_pattern(input: &str) -> IResult<&str, MatchPattern> {
    let (input, _) = whitespace_handler(input)?;
    let (rest, name) = ws(parse_identifier)(input)?;
    if name == "_" {
        Ok((rest, MatchPattern::Wildcard))
    } else {
        Ok((rest, MatchPattern::Identifier(name.to_string())))
    }
}

fn parse_number<'a>(original_input: &'a str) -> impl FnMut(&'a str) -> IResult<&'a str, Expr> {
    move |input: &'a str| {
        let start = input.as_ptr() as usize - original_input.as_ptr() as usize;

        if let Ok((input, float_str)) = recognize::<_, _, Error<&str>, _>(tuple((
            opt(char('-')),
            digit1,
            alt((
                recognize(tuple((
                    char('.'),
                    digit1,
                    opt(tuple((
                        alt((char('e'), char('E'))),
                        opt(alt((char('+'), char('-')))),
                        digit1,
                    ))),
                ))),
                recognize(tuple((
                    alt((char('e'), char('E'))),
                    opt(alt((char('+'), char('-')))),
                    digit1,
                ))),
            )),
        )))(input)
        {
            let len = float_str.len();
            if let Ok(value) = float_str.parse::<f64>() {
                return Ok((
                    input,
                    Expr::float(value, calc_range(original_input, start, len)),
                ));
            }
        }

        let (input, int_str) = recognize(tuple((opt(char('-')), digit1)))(input)?;
        let len = int_str.len();

        if let Ok(value) = int_str.parse::<i64>() {
            Ok((
                input,
                Expr::int(value, calc_range(original_input, start, len)),
            ))
        } else {
            Err(nom::Err::Error(Error::new(
                input,
                nom::error::ErrorKind::Digit,
            )))
        }
    }
}

fn parse_string_literal<'a>(
    original_input: &'a str,
) -> impl FnMut(&'a str) -> IResult<&'a str, Expr> {
    move |input: &'a str| {
        let start = input.as_ptr() as usize - original_input.as_ptr() as usize;

        let (input, _) = char('\'')(input)?;
        let (input, content) = take_while(|c| c != '\'')(input)?;
        let (input, _) = char('\'')(input)?;

        let len = content.len() + 2;

        Ok((
            input,
            Expr::string(content.to_string(), calc_range(original_input, start, len)),
        ))
    }
}

#[test]
fn test_temp() {
    let my_str = "(jacob.jacobman.value)()*()*))".to_string();
    match parse_expr(&my_str, &my_str, &mut Vec::new()) {
        Ok(r) => {
            println!("We parsed it as:");
            println!("{}", r.1.kind);

            if let ExprKind::FieldAccess { object, field } = r.1.kind {
                println!("Obj: {}, field: {}", object.kind, field);
            }
        }
        Err(_) => {
            println!("Failed to parse it");
        }
    }
}
